baseURL: https://www.mikael.dev/
title: Mikael Weaver
defaultcontentlanguage: en
languageCode: en-us
pluralizelisttitles: false
pagination:
  pagerSize: 21
disableKinds: ["taxonomy"]
enableRobotsTXT: true
relativeURLs: false

params:
  img_sizes: [480, 768, 1200, 1400, 1700, 2000, 2436]
  srcset_img_prefix: https://mikaeldevcdn.blob.core.windows.net/
  header_logo:
    alt: ''
    src: img/Mikael-0233-zoomed.jpg

markup:
  defaultMarkdownHandler: goldmark
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  goldmark:
    parser:
      wrapStandAloneImageWithinParagraph: false
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: true
      unsafe: false
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    noClasses: true
    style: monokai
    tabWidth: 4

taxonomies:
  category: categories
  tag: tag

build:
  buildStats:
    enable: true
  cachebusters:
  - source: assets/notwatching/hugo_stats\.json
    target: css
  - source: (postcss|tailwind)\.config\.js
    target: css
  - source: assets/css/main.css
    target: css

module:
  hugoVersion:
    min: "0.134.2"
  mounts:
  - source: assets
    target: assets
  - disableWatch: true
    source: hugo_stats.json
    target: assets/notwatching/hugo_stats.json
  - source: node_modules
    target: assets