baseURL: https://www.mikael.dev/
title: Mikael Weaver
languagecode: en
pluralizelisttitles: false
paginate: 21
disableKinds: ["taxonomyTerm"]

params:
  img_sizes: [480, 768, 1200, 1400, 1700, 2000, 2436]
  srcset_img_prefix: https://mikaeldevsite.blob.core.windows.net/
  header_logo: {alt: '', src: img/Mikael-0233-zoomed.jpg}

relativeURLs: false
title: mikael.dev
blackfriday:
  extensions:
  - hardLineBreak
  - noEmptyLineBeforeBlock
taxonomies:
  category: categories
  tag: tag