name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: "Setup Node 12"
      uses: actions/setup-node@v1
      with:
        node-version: 12
        
    - name: "Install Node Packages" 
      run: npm install
        
    - name: Setup Python
      uses: actions/setup-python@v1.2.0
    
    - name: "Install Python Packages"
      run: pip install -r requirements.txt

    - name: "Login to Azure CLI"
      run: az login --service-principal -u "$ARM_CLIENT_ID" -p "$ARM_CLIENT_SECRET" -t "$ARM_TENANT_ID"
      env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    - name: "Pull Srcset file"
      run: |
        export CDN_BLOB_ACCOUNT_KEY=$(az storage account keys list --account-name ${{ secrets.CDN_BLOB_ACCOUNT_NAME }} --output tsv --query '[0].value')
        npm run-script pull-srcsets
      env:
        CDN_BLOB_ACCOUNT_NAME: ${{ secrets.CDN_BLOB_ACCOUNT_NAME }}
    
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build Hugo Sitedev
      run: hugo --minify
    
    - name: "Upload as Artifact"
      uses: actions/upload-artifact@v1
      with:
        name: HugoBuildOutput
        path: ./public
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: kheiakiyama/install-azcopy-action@v1
      with:
        version: 'v10'
    
    - name: Download Artifact
      uses: actions/download-artifact@v1
      with:
        name: HugoBuildOutput
        path: ./public
    
    - name: "Copy Static Site to Azure"
      run: |
        azcopy_v10 login --service-principal --application-id "$ARM_CLIENT_ID" --tenant-id "$ARM_TENANT_ID"
        azcopy_v10 copy "./public/*" "https://${{ secrets.SITE_BLOB_ACCOUNT_NAME }}.blob.core.windows.net/\$web" --recursive
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        AZCOPY_SPA_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
