name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: "Setup Node 12"
      uses: actions/setup-node@v1
      with:
        node-version: 12
        
    - name: "Install Node Packages"
      run: npm install
        
    - name: Setup Python
      uses: actions/setup-python@v1.2.0
    
    - name: "Install Python Packages"
      run: pip install -r requirements.txt
    
    - name: "Pull Srcset files"
      run: |
        export BLOB_ACCOUNT_KEY=$(az storage account keys list --account-name ${{ secrets.BLOB_ACCOUNT_NAME }} --output tsv --query '[0].value')
        npm run-script pull-srcsets
      env:
        BLOB_ACCOUNT_NAME: ${{ secrets.BLOB_ACCOUNT_NAME }}
    
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build Hugo Sitedev
      run: hugo --minify
    
    - name: "Upload as Artifact"
      uses: actions/upload-artifact@v1
      with:
        name: HugoBuildOutput
        path: ./public
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: kheiakiyama/install-azcopy-action@v1
      with:
        version: 'v10'
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Download Artifact
      uses: actions/download-artifact@v1
      with:
        name: HugoBuildOutput
        path: ./public
    
    - name: "Copy Static Site to Azure"
      run: |
        end=`date -u -d "5 minutes" '+%Y-%m-%dT%H:%M:%SZ'`
        sas=$(az storage account generate-sas --output tsv --account-name "${{ secrets.BLOB_ACCOUNT_NAME }}" --services b --resource-types sco --permissions cdlruwap  --expiry $end)
        azcopy_v10 copy --source "./public/*" --destination "https://${{ secrets.BLOB_ACCOUNT_NAME }}.blob.core.windows.net/\$web?$sas" --recursive --overwrite
