name: CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: "Setup Node 12"
      uses: actions/setup-node@v1
      with:
        node-version: 12
        
    - name: Setup Python
      uses: actions/setup-python@v1.2.0
    
    - name: Install hugo + azcopy
      run: |
        echo "installing hugo"
        sudo mkdir -p /home/hugo/
        curl -L https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_0.74.3_Linux-64bit.tar.gz | tar -zxf - --directory /home/hugo/
        sudo mv /home/hugo/hugo /usr/bin/
        echo "installing azcopy"
        sudo mkdir -p /home/azcopy/
        curl -L https://aka.ms/downloadazcopy-v10-linux | tar -zxf - --directory /home/azcopy/
        sudo mv $(find /home/azcopy/ -type f -name azcopy) /usr/bin/

    - name: Build and Deploy
      run: |
        alias azcopy='azcopy_v10'
        make deploy-site
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
        CDN_BLOB_ACCOUNT_NAME: ${{ secrets.CDN_BLOB_ACCOUNT_NAME }}
        SITE_BLOB_ACCOUNT_NAME: ${{ secrets.SITE_BLOB_ACCOUNT_NAME }}